### ISSUE TITLE
Won't work with macOS/Metal

### ISSUE THREAD

**Issue by Meorge** [raphael-ernaelsten/Aura#26]
Whenever I try to open one of the example scenes from Aura on my Mac, I get the following error:

`NullReferenceException: Object reference not set to an instance of an object
AuraAPI.Frustum.Dispose () (at Assets/Aura/Classes/Frustum.cs:330)
AuraAPI.Aura.DisposeFrustrum () (at Assets/Aura/Classes/Aura.cs:359)
AuraAPI.Aura.OnDisable () (at Assets/Aura/Classes/Aura.cs:149)
UnityEngine.Behaviour:set_enabled(Boolean)
AuraAPI.Aura:OnEnable() (at Assets/Aura/Classes/Aura.cs:135)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`

I've tried reimporting `ComputeDataComputeShader.compute` once at this point as per the readme, and the error persists.

I'm running 2017.3.0f3 Personal on macOS 10.13.4.

**Comment by Meorge** [comment]
So I did a bit of sleuthing, and it looks like the reason it's not working is that the required shader model is 5.0 (`SystemInfo.graphicsShaderLevel >= 50` in `CheckCompatibility()` from `Aura.cs`) but my computer returns `SystemInfo.graphicsShaderLevel = 45`.

It looks like the Aura shaders thus need to be lowered from Shader Model 5.0 to around 3.5.

**Comment by raphael-ernaelsten** [comment]
I love when people test my nerves 😈 

Sir, please understand that you don't understand how this works, and please read the descriptions...

**Comment by raphael-ernaelsten** [comment]
I said "testing my nerves" because I thought you were the guy that is spamming me for weeks now because he cannot make Aura work on his 5yo mac with integrated graphic chip...
There was many times stated that it doesn't work for now and that my target is DX11.
When I told you that there was no os dependency, it didn't mean it would work out of hand, it meant it could work if someone took the time to make it work...

However, I am puzzled on how you can have Aura work by just lowering the target to 3.5.
I have little experience on OpenGl but it still makes no sense to me.
Changing the target in the shader will not make the compute shader magically compile (it needs sm5 because it's a sm5 feature! + there is no link between the compute shader and the shaders).
So either you use some magic that I don't know about... or you are just cracking me up :question:

**Comment by Meorge** [comment]
Nope, that wasn't me. The only times I've interacted with you have been on that reddit thread and in this GitHub issue.

As for the target issue, it honestly is puzzling to me as well. I don't have my Unity project open right now, but I can definitely say that lowering the targets to 3.5 from 5.0, and changing the "check shader model capability" code in Aura allowed for volumetric lighting. If you'd like more proof I can try to record videos this weekend of it in action.

**Comment by syscrusher1709** [comment]
I may be able to shed some light on this (pun intended). In developing 
the custom shader for my Magic Markers asset, I found that the Mac 
behaves differently by default in the Unity editor than it does in a 
standalone Mac build, unless you change the graphics mode settings.

I don't have my Mac with me right now (I'm not at home), but between 
Metal and OpenGL, the editor and the standalone build differ in which is 
the default. One of these supports compute shaders and one does not. In 
my product, I created a shader with different fallback options for SM 
5.0 and SM 3.5, so it runs both ways on the Mac depending on which 
graphics stack is active.

Hope this helps, and sorry I can't be more specific than that without 
the Mac in front of me to refresh my memory.
